### ISSUE TITLE
`yarn generate` fails: `could not detect network `

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/protocol-contracts#184]
Generate action currently failing from an apparent network detection issue: https://github.com/zeta-chain/protocol-contracts/actions/runs/9684149526/job/26721219625

```
Generating protocol addresses...
An unexpected error occurred:
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.6.8)
    at Logger.makeError (/home/runner/work/protocol-contracts/protocol-contracts/node_modules/ethers/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/home/runner/work/protocol-contracts/protocol-contracts/node_modules/ethers/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at JsonRpcProvider.<anonymous> (/home/runner/work/protocol-contracts/protocol-contracts/node_modules/ethers/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:444:23)
    at step (/home/runner/work/protocol-contracts/protocol-contracts/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/home/runner/work/protocol-contracts/protocol-contracts/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/home/runner/work/protocol-contracts/protocol-contracts/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}
```

**Comment by fadeev** [comment]
Can't reproduce this.

**Comment by fadeev** [comment]
And it looks like it also works fine in CI.

**Comment by lumtis** [comment]
Looks like it resolved on itself, let's close it and reopen if it happens again and something needs to be fixed
