### ISSUE TITLE
`yarn localnet` throws an error

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/protocol-contracts#261]
```
[NODE] anvil_metadata - Method not supported
[NODE] hardhat_metadata
[NODE] eth_chainId
[NODE] anvil_metadata - Method not supported
[NODE] hardhat_metadata
[NODE] eth_blockNumber
[NODE] eth_chainId
[NODE] eth_chainId (2)
[NODE] eth_estimateGas
[NODE] eth_getBlockByNumber
[NODE] eth_feeHistory
[NODE] eth_maxPriorityFeePerGas
[NODE] eth_sendTransaction
[NODE]   Contract deployment: GatewayEVM
[NODE]   Contract address:    0x5fbdb2315678afecb367f032d93f642f64180aa3
[NODE]   Transaction:         0x2173c83cb1d624f3cd0c431e6637c2a18fbc6d0bd1b1b77ab9553da37f0d3d13
[NODE]   From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
[NODE]   Value:               0 ETH
[NODE]   Gas used:            3611197 of 3611197
[NODE]   Block #1:            0x8b9aadd7d60d19b188792825c8e5bed3b5b44c263227e4b05bb8f3e0177345c2
[NODE] 
[NODE] eth_chainId
[NODE] eth_getTransactionByHash
[NODE] eth_chainId
[NODE] eth_getTransactionReceipt
[NODE] eth_getCode
[WORKER] Failed to deploy contracts or set up listeners: Error: types/values length mismatch (count={"types":2,"values":1}, value={"types":[{"name":"_tssAddress","type":"address","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"address","_isParamType":true},{"name":"_zetaToken","type":"address","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"address","_isParamType":true}],"values":["0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"]}, code=INVALID_ARGUMENT, version=abi/5.7.0)
[WORKER]     at Logger.makeError (/Users/fadeev/github.com/zeta-chain/protocol-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
[WORKER]     at Logger.throwError (/Users/fadeev/github.com/zeta-chain/protocol-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
[WORKER]     at AbiCoder.encode (/Users/fadeev/github.com/zeta-chain/protocol-contracts/node_modules/@ethersproject/abi/src.ts/abi-coder.ts:101:20)
[WORKER]     at Interface._encodeParams (/Users/fadeev/github.com/zeta-chain/protocol-contracts/node_modules/@ethersproject/abi/src.ts/interface.ts:323:31)
[WORKER]     at Interface.encodeFunctionData (/Users/fadeev/github.com/zeta-chain/protocol-contracts/node_modules/@ethersproject/abi/src.ts/interface.ts:378:18)
[WORKER]     at getInitializerData (/Users/fadeev/github.com/zeta-chain/protocol-contracts/node_modules/@openzeppelin/hardhat-upgrades/src/utils/initializer-data.ts:17:30)
[WORKER]     at Proxy.deployProxy (/Users/fadeev/github.com/zeta-chain/protocol-contracts/node_modules/@openzeppelin/hardhat-upgrades/src/deploy-proxy.ts:48:36)
[WORKER]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[WORKER]     at async deploySystemContracts (/Users/fadeev/github.com/zeta-chain/protocol-contracts/scripts/worker.ts:17:22)
[WORKER]     at async startWorker (/Users/fadeev/github.com/zeta-chain/protocol-contracts/scripts/worker.ts:120:27) {
[WORKER]   reason: 'types/values length mismatch',
[WORKER]   code: 'INVALID_ARGUMENT',
[WORKER]   count: { types: 2, values: 1 },
[WORKER]   value: {
[WORKER]     types: [ [ParamType], [ParamType] ],
[WORKER]     values: [ '0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC' ]
[WORKER]   }
[WORKER] }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[WORKER] wait-on tcp:8545 && yarn worker exited with code 1
```

```
node -v
v20.15.1
```

**Comment by fadeev** [comment]
Seems like Gateway EVM needs TSS and ZETA token address:

https://github.com/zeta-chain/protocol-contracts/blob/2b8508efce14a39dfcd693dbd58915138240c699/contracts/prototypes/evm/GatewayEVM.sol#L50-L61

But only gets the TSS address:

https://github.com/zeta-chain/protocol-contracts/blob/2b8508efce14a39dfcd693dbd58915138240c699/scripts/worker.ts#L17-L20
